DROP TABLE IF EXISTS M_QUESTION;
DROP TABLE IF EXISTS M_CHOICES;
DROP TABLE IF EXISTS T_RESULT;

CREATE TABLE M_QUESTION(
	QUESTION_ID SERIAL PRIMARY KEY,
	QUESTION TEXT NOT NULL,
	CATEGORY CHARACTER VARYING (100) DEFAULT '',
	SUB_CATEGORY CHARACTER VARYING (100) DEFAULT '',
	ANSWER_EXPLAINATION TEXT DEFAULT '',
	CREATE_DATE TIMESTAMP WITHout TIME ZONE,
	UPDATE_DATE TIMESTAMP WITHout TIME ZONE,
	DELETEFLAG NUMERIC (2) DEFAULT 0
);

CREATE TABLE M_CHOICES (
	CHOICE_ID SERIAL PRIMARY KEY,
	QUESTION_ID INTEGER NOT NULL,
	CHOICE CHARACTER VARYING (250) NOT NULL,
	CREATE_DATE TIMESTAMP WITHout TIME ZONE,
	UPDATE_DATE TIMESTAMP WITHout TIME ZONE,
	DELETEFLAG NUMERIC (2) DEFAULT 0
);

CREATE TABLE T_RESULT (
	QUIZ_ID SERIAL PRIMARY KEY,
	QUIZ_SCORE NUMERIC(5),
	QUIZ_ITEMS NUMERIC(5),
	DATE_TAKEN TIMESTAMP WITHout TIME ZONE,
	DELETEFLAG NUMERIC (2) DEFAULT 0
);


--https://gist.github.com/ajjain/e7c8bf71b87cefc7375e
INSERT INTO M_QUESTION (QUESTION, ANSWER_EXPLAINATION, CREATE_DATE, UPDATE_DATE) VALUES
('SAMPLE QUESTION', 'THIS IS AN EXPLANATION', current_timestamp,current_timestamp)
RETURNING QUESTION_ID;

--multiple add ons
--https://getbootstrap.com/docs/4.0/components/input-group/

SELECT * FROM M_QUESTION
